export const links = [
  {
    id: 1,
    url: '/',
    text: 'Home',
  },
  {
    id: 2,
    url: '/about',
    text: 'About',
  },
  {
    id: 3,
    url: '/skills',
    text: 'Skills',
  },
  {
    id: 4,
    url: '/work',
    text: 'Work',
  },
  {
    id: 5,
    url: '/testimonial',
    text: 'Testimonial',
  },
  {
    id: 6,
    url: '/blog',
    text: 'Blog',
  },
  {
    id: 7,
    url: '/team',
    text: 'Team',
  },
  {
    id: 8,
    url: '/contact',
    text: 'Contact',
  },
]
export const works = [
  {
    id: 1,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design1.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 2,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design1.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 3,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page1.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 4,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress1.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 5,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design2.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 6,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design2.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 7,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page2.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 8,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress2.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 9,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress3.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 10,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design3.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 11,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design3.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 12,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design4.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 13,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design4.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 14,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page3.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 15,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress4.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 16,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design5.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 17,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design5.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 18,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page4.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 19,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress5.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 20,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress6.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 21,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design6.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 22,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design6.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 23,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page5.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 24,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress7.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 25,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design7.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 26,
    title: 'Graphic Design',
    category: 'Graphic Design',
    price: 299.99,
    img: '../images/graphic design/graphic-design8.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 27,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page6.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 28,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page7.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 29,
    title: 'Landing Pages',
    category: 'Landing Pages',
    price: 299.99,
    img: '../images/landing page/landing-page3.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 30,
    title: 'Wordpress',
    category: 'Wordpress',
    price: 299.99,
    img: '../images/wordpress/wordpress8.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 31,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design7.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
  {
    id: 32,
    title: 'Web Design',
    category: 'Web Design',
    price: 299.99,
    img: '../images/web design/web-design2.jpg',
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex magnam dicta repudiandae totam eum enim recusandae sequi, ratione sit a!`,
  },
]
export const options = [
  {
    id: 1,
    img: '../images/options/1.png',
    text: 'different theme option',
  },
  {
    id: 2,
    img: '../images/options/2.png',
    text: 'fully customizable',
  },
  {
    id: 3,
    img: '../images/options/3.png',
    text: 'unlimited support',
  },
  {
    id: 4,
    img: '../images/options/4.png',
    text: 'responsive all device',
  },
]

export const servicesData = [
  {
    id: 1,
    title: 'Web design',
    img: '../images/graphic design/graphic-design6.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Deserunt mollit anim id est laborum. Loret, consectetur adip isicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 2,
    title: 'Graphic Design',
    img: '../images/graphic design/graphic-design7.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adip isicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 3,
    title: 'Online Support',
    img: '../images/graphic design/graphic-design8.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adip isicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 4,
    title: 'App Design',
    img: '../images/graphic design/graphic-design9.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adip isicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ',
  },
  {
    id: 5,
    title: 'Online Marketing',
    img: '../images/graphic design/graphic-design10.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adi ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adip isicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 6,
    title: 'Seo Service',
    img: '../images/graphic design/graphic-design11.jpg',
    text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adip isicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
]

export const news = [
  {
    id: 1,
    title: 'Seo Service',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/1.jpg',
    comments: 3,
    date: 12,
    mounth: 'Feb',
  },
  {
    id: 2,
    title: 'Amazing Blog Post',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/2.jpg',
    comments: 10,
    date: 10,
    mounth: 'Feb',
  },
  {
    id: 3,
    title: 'Amazing Blog Post',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/3.jpg',
    comments: 8,
    date: 11,
    mounth: 'Feb',
  },
  {
    id: 4,
    title: 'Seo Service',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/4.jpg',
    comments: 2,
    date: 13,
    mounth: 'Feb',
  },
  {
    id: 5,
    title: 'Seo Service',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/5.jpg',
    comments: 2,
    date: 9,
    mounth: 'Feb',
  },
  {
    id: 6,
    title: 'Amazing Blog Post',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/6.jpg',
    comments: 3,
    date: 11,
    mounth: 'Feb',
  },
  {
    id: 7,
    title: 'Seo Service',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/7.jpg',
    comments: 6,
    date: 12,
    mounth: 'Feb',
  },
  {
    id: 8,
    title: 'Seo Service',
    author: 'admin',
    ulr: 'sss',
    img: '../images/news/8.jpg',
    comments: 10,
    date: 12,
    mounth: 'Feb',
  },
]

export const people_data = [
  {
    id: 1,
    photo: '../images/news/1.jpg',
    name: 'Lisa',
    title: 'Web desiner',
    text: ' Integer dignissim, augue tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis. Tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis.',
  },

  {
    id: 2,
    photo: '../images/news/2.jpg',
    name: 'Tom',
    title: 'Web desiner',
    text: ' Integer dignissim, augue tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis. Tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis.',
  },
  {
    id: 3,
    photo: '../images/news/3.jpg',
    name: 'Jack',
    title: 'Web desiner',
    text: ' Integer dignissim, augue tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis. Tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis.',
  },
  {
    id: 4,
    photo: '../images/news/4.jpg',
    name: 'Jerry',
    title: 'Web desiner',
    text: ' Integer dignissim, augue tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis. Tempus ultricies luctus, quam dui laoreet sem, non dictum odio nisi quis massa. Morbi pulvinar odio eget aliquam facilisis.',
  },
]
